#日志系统记录的日志
catsyslog:
  logpath: "D:/golangwork/src/golang-/logcatchsys/logdata"
  loglevel: "debug" 

#采集其他系统的日志目录

collectlogs:
#  - logpath: "D:/golangwork/src/golang-/logcatchsys/logdir1/log.txt"
#    logtopic: "logdir1"
#  - logpath: "D:/golangwork/src/golang-/logcatchsys/logdir2/log.txt"
#    logtopic: "logdir2"
#  - logpath: "D:/golangwork/src/golang-/logcatchsys/logdir3/log.txt"
#    logtopic: "logdir3"
  
  - logpath: "/home/secondtonone/workspace/goProject/src/golang-/logcatchsys/logdir2/log.txt"
    logtopic: "logdir2"
  - logpath: "/home/secondtonone/workspace/goProject/src/golang-/logcatchsys/logdir3/log.txt"
    logtopic: "logdir3"

#etcd存储的监控日志的键值
etcdkeys:
  #- "collectlogkey1"
  #- "collectlogkey2"
etcdconfig:
  - "localhost:2379" 
  - "localhost:3379"
  - "localhost:4379"
kafkaconfig:
  kafkaaddr: "localhost:9092"
elasticconfig:
  elasticaddr: "localhost:9200"
  typestr: "catlog"




  
